--- #YAML:1.0
name:                Fuse-TM
version:             0.1
abstract:            Accessing Topic Maps as Filesystem
license:             perl
author:              
    - Alexander Zangerl <alphazulu@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Data::Dumper:                  0
    Fuse:                          0.09
    Test::More:                    0.47
    TM:                            1.43
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
