--- #YAML:1.0
name:               Fuse-TM
version:            0.2
abstract:           Accessing Topic Maps as Filesystem
author:
    - Alexander Zangerl <alphazulu@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:  0
    Fuse:          0.09
    Test::More:    0.47
    TM:            1.43
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
